name: Build and Test

on:
  push:
    branches:
      #- main
      - ci-cd-files  # Include other branches if needed
  pull_request:
    branches:
      #- main
      - ci-cd-files  # Include other branches if needed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [9.0]  # Use the version of .NET your project is targeting
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
