name: Build and Test

on:
  push:
    branches:
      #- main
      - ci-cd-files  # Include other branches if needed
  pull_request:
    branches:
      #- main
      - ci-cd-files  # Include other branches if needed

jobs:
  build:
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.101
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore #--configuration Release

      - name: Run tests
        run: dotnet test --no-restore #--configuration Release --no-build --verbosity normal
